name: "Update README"

on: [push]

jobs:
  build:
    strategy:
      matrix:
        qt_version: [5.14.2]
        platform: [windows-latest]
        arch: [x64]
        include: 
          - platform: windows-latest
            arch: x64
            qtarch: win64_msvc2017_64
            cmakearch: x64
      fail-fast: false

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checking out sources
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
# =========================================================================================================
      - name: Install MSVC compiler
        uses: ilammy/msvc-dev-cmd@v1
        with: 
          toolset: 14.2
          arch: ${{ matrix.arch }}
      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v1
        with:
          path: ../Qt
          key: QtCache-${{ matrix.platform }}-${{ matrix.arch }}-${{ matrix.qt_version }}
      - name: Installing Qt - ${{ matrix.arch }}
        uses: jurplel/install-qt-action@v2.5.0
        with:
          version: ${{ matrix.qt_version }}
          arch: ${{ matrix.qtarch }}
          mirror: 'http://mirrors.ocf.berkeley.edu/qt/'
          cached: ${{ steps.cache-qt.outputs.cache-hit }}
      - name: Build
        if: matrix.platform == 'windows-latest'
        env:
          CC: cl.exe
          CXX: cl.exe
        run: |
          cd tools/rdme-files-upd
          mkdir build
          cd build
          cmake .. 
          cmake --build .
      - name: Update README
        if: matrix.platform == 'windows-latest'
        env:
          CC: cl.exe
          CXX: cl.exe
        run: |
          cd tools/rdme-files-upd/build
          choco install tree
          tree .
          ./Debug/rdme-files-upd.exe
      - name: Check diff
        run: git diff --exit-code HEAD
      - name: Create Pull Request
        if: failure()
        uses: peter-evans/create-pull-request@v2
        with:
          commit-message: "docs: Update README"
          title: "Update README for ${{ github.ref }}"
          labels: "auto-pr/docs"
          assignees: "${{ github.actor }}"
          reviewers: "${{ github.actor }}"
          branch: "auto-pr/upd-readme/${{ github.ref }}"

              